print("Must run in Terminal to input numbers!")
firstNum = input("Enter your first number: ")
firstNum = int(firstNum)
secondNum = input("Enter your second number: ")
secondNum = int(secondNum)
print("The difference of your numbers are: ",firstNum - secondNum)